# Generated by Django 5.1.7 on 2025-03-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screener_type', models.CharField(choices=[('intraday', 'Intraday Screener'), ('short_term', 'Short Term'), ('long_term', 'Long Term'), ('multibagger', 'Multi Bagger'), ('intraday_multibagger', 'Intraday Multi Bagger')], max_length=50)),
                ('stock_symbol', models.CharField(max_length=20)),
                ('stock_name', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
