# Generated by Django 5.1.7 on 2025-04-01 04:48

import django.db.models.deletion
import screeners.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screeners', '0003_whatsapplead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapplead',
            name='end_date',
            field=models.DateTimeField(default=screeners.models.default_end_date),
        ),
        migrations.AddField(
            model_name='whatsapplead',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
