# Generated by Django 5.1.7 on 2025-04-01 04:54

import screeners.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screeners', '0004_whatsapplead_end_date_whatsapplead_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapplead',
            name='end_date',
            field=models.DateTimeField(default=screeners.models.default_end_date, null=True),
        ),
    ]
