# Generated by Django 5.1.7 on 2025-04-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screeners', '0005_alter_whatsapplead_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapplead',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
